[package]
name = "rust_slack_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
base64 = "0.22.1"
chrono = "0.4.39"
dotenvy = "0.15.7"
futures = "0.3.31"
serde_derive = "1.0.217"
serde_json = "1.0.138"
